FROM python:3.6
LABEL maintainer "support@riddleandcode.com"

ARG TM_VERSION=0.22.8
ARG MONIT_VERSION=5.26.0
ARG MONGO_VERSION=4.2

RUN mkdir -p /usr/src/app
ENV HOME /root
COPY . /usr/src/app/
WORKDIR /usr/src/app

# Install BigchainDB
RUN apt-get -qq update \
    && apt-get -y upgrade \
    && apt-get install -y jq \
    && pip install --upgrade pip \
    && pip install . \
    && apt-get autoremove \
    && apt-get clean

# Install monit
RUN wget https://mmonit.com/monit/dist/binary/$MONIT_VERSION/monit-$MONIT_VERSION-linux-x64.tar.gz \
    && tar zxvf monit-$MONIT_VERSION-linux-x64.tar.gz \
    && cp monit-$MONIT_VERSION/bin/monit /usr/bin/ \
    && cp monit-$MONIT_VERSION/conf/monitrc /etc/

# Install mongodb
RUN wget -qO - https://www.mongodb.org/static/pgp/server-$MONGO_VERSION.asc \
        | apt-key add - \
    && echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/$MONGO_VERSION multiverse" \
        | tee /etc/apt/sources.list.d/mongodb-org-$MONGO_VERSION.list \
    && apt-get update \
    && apt-get install -y mongodb-org


# Install Tendermint
RUN wget https://github.com/tendermint/tendermint/releases/download/v${TM_VERSION}/tendermint_${TM_VERSION}_linux_amd64.zip \
    && unzip tendermint_${TM_VERSION}_linux_amd64.zip \
    && mv tendermint /usr/local/bin/ \
    && rm tendermint_${TM_VERSION}_linux_amd64.zip

ENV TMHOME=/tendermint

# Set permissions required for mongodb
RUN mkdir -p /data/db /data/configdb \
        && chown -R mongodb:mongodb /data/db /data/configdb

# BigchainDB enviroment variables
ENV BIGCHAINDB_DATABASE_PORT 27017
ENV BIGCHAINDB_DATABASE_BACKEND localmongodb
ENV BIGCHAINDB_SERVER_BIND 0.0.0.0:9984
ENV BIGCHAINDB_WSSERVER_HOST 0.0.0.0
ENV BIGCHAINDB_WSSERVER_SCHEME ws

ENV BIGCHAINDB_WSSERVER_ADVERTISED_HOST 0.0.0.0
ENV BIGCHAINDB_WSSERVER_ADVERTISED_SCHEME ws
ENV BIGCHAINDB_TENDERMINT_PORT 26657

VOLUME /data/db /data/configdb /tendermint

EXPOSE 27017 28017 9984 9985 26656 26657 26658

WORKDIR $HOME
ENTRYPOINT ["/usr/src/app/pkg/scripts/all-in-one.bash"]
